# serverless.yml

service: worldsle

plugins:
  - serverless-python-requirements
  - serverless-apigw-binary
  - serverless-wsgi

custom:
  apigwBinary:
    types:
      - '*/*'
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: false

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-2

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'
    environment:
      API_STATS_URL: ${env:API_STATS_URL}
      API_KEY: ${env:API_KEY}
